name: Fetch orig branch

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [gh/**/base]

jobs:

  pr_base_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get PR base branch
        id: get_pr_base_branch
        run: |
          orig_branch="${{ github.base_ref }}"
          echo "$orig_branch"
          orig_branch=$(echo "$orig_branch" | sed 's|/base$|/orig|')
          echo "$orig_branch"

          WAIT_SECONDS=600
          end=$((SECONDS+WAIT_SECONDS))
          branch_exists=0
          while [ $SECONDS -lt $end ]; do
           git fetch --prune origin "${orig_branch}"
           if git rev-parse --verify "origin/${orig_branch}"; then
             branch_exists=1
             break
           fi
           echo "Waiting for branch ${orig_branch} to exist..."
           sleep 30  # Wait for 30 seconds before retrying
          done
          if [ $branch_exists -eq 0 ]; then
           echo "Branch not found after ${WAIT_SECONDS} seconds"
           exit 1
          fi