name: Test composite

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

jobs:
  bc_linter:
    runs-on: ubuntu-latest
    steps:
        - name: Run BC Lint Action
          uses: izaitsevfb/pr-head-test/.github/actions/test-composite-output@test-composite